### ISSUE TITLE
[TODO] Reveal the runtime env via the framework-provided context

### ISSUE THREAD

**Issue by webknjaz** [sanitizers/octomachinery#13]
I'm thinking of:
- _(bool)_ `RUNTIME_CONTEXT.IS_GITHUB_APP`
- _(bool)_ `RUNTIME_CONTEXT.IS_GITHUB_ACTION`
- _(enum: APP|ACTION)_ `RUNTIME_CONTEXT.RUNTIME_ENV` (type?)

@ekohl what do you think?

**Comment by ekohl** [comment]
I'm not sure how you would change behavior based on if it's an app or an action. That's the most important to make a choice.

For variables I'm leaning to an enum since you don't need both and if there would be a third, it's also easier to implement. I do think `RUNTIME_ENV` is a bit ambiguous and as a new user I wouldn't know how to interpret it. `RUNTIME_TYPE`, `RUNTIME_TARGET` or `GITHUB_TARGET` come to mind.

**Comment by webknjaz** [comment]
The behavior can be simplified sometimes in case of an Action.
One example would be that in a GitHub App you might need to do some API query to get a config file from the repo while within Action it's already checked out so you can just check what's in your file system...

**Comment by webknjaz** [comment]
To be clear, I have no intention of affecting the framework behavior itself other than pre-filling these values before invoking the event handlers...

**Comment by webknjaz** [comment]
And I agree that the last variable name needs to be improved but I have no idea of how to name it best.
Maybe just stop on two boolean vars with no third one? I'm pretty sure that users would only use those as `if RUNTIME_CONTEXT.IS_GITHUB_ACTION: use_this_way()` which could be also expanded into another helper decorator for handlers just for filtering out the env and doing nothing based on that...

**Comment by webknjaz** [comment]
`@if_action_only`/`@if_app_only` kind of stuff...

**Comment by ekohl** [comment]
If the difference is a checkout, you can also think about a `get_checkout` helper (or similar) that uses the one that's already available in actions or imitates it in apps.

**Comment by webknjaz** [comment]
It's not the only difference. The number of APIs accessible is limited, API calls don't cause events, container run time is limited to ~58min and so on... I think it's very useful to have these flags. You can even enable some debugging depending on those.

**Comment by webknjaz** [comment]
I consider this solved for now. As a bonus, I've also added https://github.com/sanitizers/octomachinery/commit/c44ea605348785bbf3e15f2bde9810ce65363c2e.
